version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server
    expose:
      - "6379"

  celery-monitor:
    image: lojaconectada/celery-monitor
    env_file: .env
    command: /opt/app/celery-monitor/run_server.sh
    volumes:
      - /etc/localtime/:/etc/localtime
    expose:
      - "8905"
    networks:
      - lojaconectada-frontend
    depends_on:
      - "redis"

networks:
  lojaconectada-frontend:
    external:
      name: lojaconectada-frontend
